### ISSUE TITLE
Greece EL causes random crashes

### ISSUE THREAD

**Issue by kedzior** [kantoniak/discrete-fox#14]
Greece EL causes random crashes

http://ec.europa.eu/eurostat/statistics-explained/index.php/Glossary:Country_codes

**Comment by kantoniak** [comment]
Offline talk: we agreed to use EU codes when available, then two-letter ISO.

TODO:
- Include this info in README
- Rename country name plates
- Rename country_* files in raw folder
- ?

**Comment by kantoniak** [comment]
I would also create `CountryNameUtil` to translate codes to full names, in multiple flavors (as returned from Eurostat, to short country name etc.). Can we reuse something from your downloader @kedzior?

**Comment by kedzior** [comment]
Actually it wasn't Greece, but the Netherlands. NE->NL
https://github.com/kantoniak/discrete-fox/commit/55f8596b9661ed1d7b348cf5207e0a3ac2f08c2a

I would stay with two-letter ISO codes. It works nicely now.

TODO:
- **Include this info in README**
- _Rename country name plates - DONE_
- _Rename country_* files in raw - DONE_
- **Unify List<String> with country codes**

**Comment by kedzior** [comment]
https://github.com/kantoniak/discrete-fox/commit/ec7f267e9559469d23541cb7d0c2fb1dd330af1e

TODO:

- _Include this info in README - DONE_
- _Rename country name plates - DONE_
- _Rename country* files in raw - DONE_
- **Unify List<String> with country codes**

**Comment by kedzior** [comment]
https://github.com/kantoniak/discrete-fox/commit/43bab6759905426a75415ae42dcb6ed9b45c9420

TODO:

- _Include this info in README - DONE_
- _Rename country name plates - DONE_
- _Rename country\_* files in raw - DONE_
- _Unify List with country codes - DONE_
