### ISSUE TITLE
Add feedback on answer screen

### ISSUE THREAD

**Issue by kantoniak** [kantoniak/discrete-fox#36]
@mazurki need a doc how feedback should look

**Comment by mazurki** [comment]
![answers-feedback](https://user-images.githubusercontent.com/26678475/39960196-a8932194-561e-11e8-877d-56e9e1a648c3.PNG)

**Comment by kedzior** [comment]
https://github.com/kantoniak/discrete-fox/commit/701820c17ac0170c5c0c866ea33d213ab1799201
