### ISSUE TITLE
Remove all non-UI gameplay stuff out of MainActivity

### ISSUE THREAD

**Issue by kantoniak** [kantoniak/discrete-fox#6]
Please create a method in `Question` that returns a list of `Answers` to update recycler view.

**Comment by kantoniak** [comment]
It would be nice to group all classes like `Question`, `Answer` from `AnswerAdapter` etc. in its own package.

**Comment by kedzior** [comment]
Added getAnswers method to Question class.
https://github.com/kantoniak/discrete-fox/commit/688f68b9aa60cce3b5e110ed2852b9a81484c7ec
Put Question, Answer, etc. into ask package.
https://github.com/kantoniak/discrete-fox/commit/4edebfdaf5843c46832f3b695de63e0149574acd

**Comment by kedzior** [comment]
https://github.com/kantoniak/discrete-fox/commit/945d96ef13437eff423be20f1c27edfdedfab7c4
